---
title: Analyzing Eye-tracking Data
author: Josef Klafka and Dan Yurovsky
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show 
---

```{r setup, include=FALSE}
# load packages
library(tidyverse)
library(knitr)
library(lme4)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = FALSE, tidy = FALSE)

theme_set(theme_classic(base_size = 16))
```

```{r load_data}
load("psc.data.rda")
load("demonic.rda") 
load("dmorph.rda")
load("HU_tracking_all_stats_em.RData")
```

```{r process_data}
# ------------------------------------------------------------------------------
# PSC
# ------------------------------------------------------------------------------
psc <- dx %>%
  select(id, nw, wn, dur, wrd, sn) %>%
  as_data_frame() %>%
  mutate(dur = exp(dur)) %>%
  rename(cnd = sn, sub = id, id = wrd) %>%
  mutate(sub = as.numeric(as.factor(sub))) %>%
  mutate(cnd = as.numeric(as.factor(cnd)))

# ------------------------------------------------------------------------------

all_words_psc <- psc %>%
  distinct(nw, cnd) %>%
  group_by(cnd) %>%
  nest() %>%
  mutate(sens = map(data, ~data_frame(wn = 1:.x$nw, nw = .x$nw, dur = 0))) %>%
  select(-data) %>%
  unnest() %>%
  left_join(psc %>% distinct(sub, cnd), by = "cnd") %>%
  anti_join(psc, c("cnd", "wn", "nw", "sub")) %>%
  mutate(type = "absent")

complete_psc <- psc %>%
  select(sub, nw, wn, dur, cnd) %>%
  mutate(type = "present") %>%
  bind_rows(all_words_psc) %>%
  mutate(relwn = wn/nw, exp = "PSC") %>%
  arrange(sub, cnd, wn)

# ------------------------------------------------------------------------------
# DEMONIC
# ------------------------------------------------------------------------------
#DEMONIC SFD, data set after trimming (sentences with fewer than 16 words, extra short and long fixations removed, etc)
demonic <- single %>%
  rename(cnd = TotalWordsinSentence, wn = NumWordInSentence, sub = Subject, 
         id = Word) %>%
  mutate(nw = cnd, relwn = wn/nw, dur = exp(GazeDur), exp = "DEMONIC") %>%
  select(sub, nw, wn, dur, id, cnd, relwn, exp) %>%
  filter(nw < 16) %>%
  as_data_frame() %>%
  mutate(sub = as.numeric(as.factor(sub))) %>%
  mutate(cnd = as.numeric(as.factor(cnd)))

all_words_demonic <- demonic %>%
  distinct(nw, cnd) %>%
  group_by(cnd) %>%
  nest() %>%
  mutate(sens = map(data, ~data_frame(wn = 1:.x$nw, nw = .x$nw, dur = 0))) %>%
  select(-data) %>%
  unnest() %>%
  left_join(psc %>% distinct(sub, cnd), by = "cnd") %>%
  anti_join(psc, c("cnd", "wn", "nw", "sub")) %>%
  mutate(type = "absent")

complete_demonic <- demonic %>%
  select(sub, nw, wn, dur, cnd) %>%
  mutate(type = "present") %>%
  bind_rows(all_words_psc) %>%
  mutate(relwn = wn/nw, exp = "DEMONIC") %>%
  arrange(sub, cnd, wn)

#DMORPH SFD, dataset after trimming.
dmorph <- affpos1 %>%
   rename(cnd = TotalWordsinSentence, wn = NumWordInSentence, sub = Subject, 
         id = Word) %>%
  mutate(nw = cnd, relwn = wn/nw, dur = exp(FixDur), exp = "DMORPH") %>%
  select(sub, nw, wn, dur, id, cnd, relwn, exp) %>%
  filter(nw < 16) %>%
  as_data_frame() %>%
  mutate(sub = as.numeric(as.factor(sub)))

all_words_dmorph <- dmorph %>%
  distinct(nw, cnd) %>%
  group_by(cnd) %>%
  nest() %>%
  mutate(sens = map(data, ~data_frame(wn = 1:.x$nw, nw = .x$nw, dur = 0))) %>%
  select(-data) %>%
  unnest() %>%
  left_join(psc %>% distinct(sub, cnd), by = "cnd") %>%
  anti_join(psc, c("cnd", "wn", "nw", "sub")) %>%
  mutate(type = "absent")

complete_dmorph <- dmorph %>%
  select(sub, nw, wn, dur, cnd) %>%
  mutate(type = "present") %>%
  bind_rows(all_words_psc) %>%
  mutate(relwn = wn/nw, exp = "DMORPH") %>%
  arrange(sub, cnd, wn)

# Hindi-Allahabad 
hindi <- etm %>%
  group_by(subj, expt, session, item, trial) %>%
  mutate(nw = max(roi)) %>%
  ungroup() %>%
  rename(wn = roi, sub = subj, id = word_lex, dur = SFD) %>%
  mutate(cnd = nw, relwn = wn/nw, sub = as.character(sub),
         exp = "HINDI") %>%
  filter(nw < 16) %>%
  select(sub, nw, wn, dur, id, cnd, relwn, exp) %>%
  mutate(sub = as.numeric(as.factor(sub)))
```

```{r combine_data}
b_all <- bind_rows(complete_psc, complete_demonic, complete_dmorph, hindi) %>%
  mutate(finpos = wn - nw,
         finposlab = as.character(finpos),
         finposnum = max(nw) + finpos)
```

```{r plot_data}
data <- b_all %>%
  group_by(exp, relwn) %>%
  summarise(dur = mean(dur)) %>%
  ungroup() %>%
  mutate(exp = factor(exp, levels = c("PSC", "DEMONIC", "DMORPH", "HINDI")))

ggplot(data, aes(x = relwn, y = dur)) + 
  facet_wrap(~exp, scales = "free_y") + 
  geom_point() + 
  geom_smooth()

```