---
title: "Eye-tracking"
author: "Joe Klafka"
date: "2/8/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytext)
library(tidyboot)
library(entropy)
library(magrittr)
library(feather)
library(here)

library(childesr)

knitr::opts_chunk$set(echo = TRUE)
```

```{r corpora}
prov_utterances <- get_utterances(corpus = "Providence") %>% 
  filter(speaker_role != "Target_Child") %>%
  mutate(words = stem)

okayama_utterances <- get_utterances(corpus = "Okayama")  %>% 
  filter(speaker_role == "Target_Child") %>%
  rename(words = gloss)

zhou_utterances <- get_utterances(corpus = "ZhouDinner") %>%
  filter(speaker_role != "Target_Child") %>%
  rename(words = stem)

shiro_utterances <- get_utterances(corpus = "Shiro") #use gloss

wagner_utterances <- get_utterances(corpus = "Wagner") #use gloss

switchboard <- read_feather(here("../switchboard/switchboard.feather")) %>%
  rename(words = value)
```

```{r ngram entropy}
# unnest_tokens(word, value, token = stringr::str_split, pattern = " +") 

# takes in a tbl of utterances the column with the actual utterances is 
# named words, along with an integer target_length and a ngram length N.
ngram_entropy <- function(utterances, target_length, N) {

  
  tokens <- utterances %>%
    mutate(length = str_count(words, pattern = "[ +]+") + 1) %>%
    filter(length == target_length) %>%
    mutate(utterance_id = 1:n()) %>%
    unnest_tokens(word, words, token = stringr::str_split, pattern = " +") %>%
    group_by(utterance_id) %>%
    mutate(word_order = 1:n())
  
    
  lags <- expand.grid(lag_n = 1:(N-1), 
                      utterance_id = unique(tokens$utterance_id))
  
  
  grams <- tokens %>%
    left_join(lags, by = "utterance_id") %>%
    group_by(utterance_id, lag_n) %>%
    arrange(utterance_id, lag_n, word_order) %>%
    mutate(lag = lag(word, n = first(lag_n))) %>%
    group_by(utterance_id, word_order, word) %>%
    summarise(gram = paste(lag, collapse = " ")) %>%
    summarise(gram = paste(gram, word, collapse = " ")) %>%
    filter(word_order >= N) %>%
    rename(gram_order = word_order) %>%
    group_by(gram_order, gram)

 grams %>%
  summarise(n = n()) %>%
  tidyboot(summary_function = function(x) x %>% 
        summarise(entropy = entropy(n, unit = "log2")),
       statistics_functions = function(x) x %>%
       summarise_at(vars(entropy), funs(ci_upper, ci_lower))) %>%
  mutate(length = target_length)
}
```

```{r childes}
## Providence
# unigrams
prov_unigrams <- map(2:10, ~ngram_entropy(prov_utterances, .x, 1)) %>% 
  bind_rows()

prov_unigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

# bigrams
prov_bigrams <- map(3:10, ~ngram_entropy(prov_utterances, .x, 2)) %>% 
  bind_rows()

prov_bigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

# trigrams
prov_trigrams <- map(4:10, ~ngram_entropy(prov_utterances, .x, 3)) %>% 
  bind_rows()

prov_trigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

write_feather(feather(prov_unigrams), here("prov/adult_unigrams.feather"))
## Zhou
# unigrams
zhou_unigrams <- map(2:10, ~ngram_entropy(zhou_utterances, .x, 1)) %>% 
  bind_rows()

zhou_unigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

# bigrams
zhou_bigrams <- map(3:10, ~ngram_entropy(zhou_utterances, .x, 2)) %>% 
  bind_rows()

zhou_bigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

# trigrams
zhou_trigrams <- map(4:10, ~ngram_entropy(zhou_utterances, .x, 3)) %>% 
  bind_rows()

zhou_trigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)


## Okayama
# bigrams 
okayama_bigrams <- map(3:10, ~ngram_entropy(okayama_utterances, .x, 2)) %>% 
  bind_rows()

okayama_bigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

# trigrams
okayama_trigrams <- map(4:10, ~ngram_entropy(okayama_utterances, .x, 3)) %>% 
  bind_rows()

okayama_trigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)
```

```{r zhou and okayama}
# bigrams
prov_bigrams <- map(3:10, ~ngram_entropy(prov_utterances, .x, 2)) %>% 
  bind_rows()

prov_bigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

# trigrams
prov_trigrams <- map(4:10, ~ngram_entropy(prov_utterances, .x, 3)) %>% 
  bind_rows()

prov_trigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)


```

```{r switchboard}
# unigrams to check against previous results
switchboard_unigrams <- map(2:10, ~ngram_entropy(switchboard, .x, 1)) %>% 
  bind_rows()

switchboard_unigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

# bigrams
switchboard_bigrams <- map(3:10, ~ngram_entropy(switchboard, .x, 2)) %>% 
  bind_rows()

switchboard_bigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

#trigrams
switchboard_trigrams <- map(4:10, ~ngram_entropy(switchboard, .x, 3)) %>% 
  bind_rows()

switchboard_trigrams %>% ggplot(aes(x = gram_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)
```





















