---
title: Non-English Conditional Entropy and Mutual Information
author: Joe Klafka
date: "`r Sys.date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show 
---

```{r setup, include=FALSE}
# load packages
library(knitr)
library(tidyverse)
library(directlabels)
library(childesr) #data
library(SnowballC) #stemmer
library(tidytext)
library(entropy)
library(tidyboot)
library(dplyr)
library(tokenizers)
library(tau)
library(gtools)
knitr::opts_chunk$set(echo = TRUE)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = FALSE, tidy = FALSE)

theme_set(theme_classic(base_size = 16))
```

```{r get_utterances}
prov_utterances <- get_utterances(corpus = "Providence")

brown_utterances <- get_utterances(corpus = "Brown")

zhou_dinner <- get_utterances(corpus = "zhoudinner")

shiro_utterances <- get_utterances(language = "SPA", corpus="Shiro") 
#Venezuelan children narrative (113 children; half 1st graders half 4th graders; half high SES half low SES)

okayama_utterances <- get_utterances(corpus = "Okayama") #mother-child conversations in the Osaka area

wagner_utterances <- get_utterances(corpus = "Wagner") #German corpus of children during daily routines (age range from 1,5 to 14,10)

miipro_utterances <- get_utterances(corpus = "miipro") #Tokyo mother-child conversations in the family's home

leveille_utterances <- get_utterances(corpus = "leveille") #longitudinal study of a French child of university profs at home

```


```{r presentation}

get_counts <- function(role, sen_length, utterances) {
  
  if(role == "Target_Child") {
    sub_utterances <- utterances %>%
      filter(speaker_role == "Target_Child") %>%
      mutate(length = str_count(gloss, " ") + 1) # uses stems of words, not original words
  } else {
     sub_utterances <- utterances %>%
      filter(speaker_role != "Target_Child") %>%
      mutate(length = str_count(gloss, " ") + 1)
  }
  
  sub_utterances %>%
    filter(length == sen_length) %>%
    mutate(utterance_id = 1:n()) %>%
    unnest_tokens(word, gloss) %>%
    group_by(utterance_id) %>%
    mutate(word_order = 1:n())
}

all_conditional_entropy <- function(df) {
  max_len <- max(df$word_order)
  perms <- permutations(max_len, 2, 1:max_len, repeats.allowed = F) 
  combs <-  setNames(split(perms, seq(nrow(perms))), rownames(perms))
  
  map(combs, ~conditional_entropy(df, .x[1], .x[2])) %>%
    bind_rows()
  
}

conditional_entropy <- function(df, X, Y) { #Y is conditioning variable
  
  d <- df %>%
    filter(word_order %in% c(X, Y)) %>%
    mutate(word_order = factor(word_order, labels = c("first", "second"))) %>%
    spread(word_order, word) 
  
  ent <- d$first %>% table() %>% as.vector() %>% entropy.empirical(unit="log2")

  mi <- d %>% 
    group_by(first, second) %>%
    summarise(n = n()) %>%
    spread(second, n, fill = 0) %>% 
    ungroup() %>%
    select(-first) %>%
    mi.empirical(., unit = "log2")

  data_frame(length = max(df$word_order), X = X, Y = Y, mi = mi, ent = ent, ce = ent - mi)
}

get_ce <- function(utterances, role) {
  
  ce <- map(2:6, ~get_counts(role, .x, utterances)) %>% 
    map(~filter(.,word_order <= length)) %>%
    map(all_conditional_entropy) %>%
    bind_rows()

  
  return(ce)
}

all_pairwise_mi <- function(df) {
  max_len <- max(df$word_order)
  
  combs <- combn(1:max_len, 2, simplify = F) 
  
  map(combs, ~position_mi(df, .x[1], .x[2])) %>%
    bind_rows()
  
}

position_mi <- function(df, pos1, pos2) {
  
  mi <- df %>%
    filter(word_order %in% c(pos1, pos2)) %>%
    mutate(word_order = factor(word_order, labels = c("first", "second"))) %>%
    spread(word_order, word) %>%
    group_by(first, second) %>%
    summarise(n = n()) %>%
    spread(second, n, fill = 0) %>% 
    ungroup() %>%
    select(-first) %>%
    mi.empirical(., unit = "log2")
  
  data_frame(length = max(df$word_order), pos1 = pos1, pos2 = pos2, mi = mi)
}

get_mi <- function(utterances, role) {
  
  mi <- map(2:6, ~get_counts(role, .x, utterances)) %>% 
    map(~filter(.,word_order <= length)) %>%
    map(all_pairwise_mi) %>%
    bind_rows()
  
  
  return(mi)
}
```

```{r work_progress}

shiro_mi_children <- get_mi(shiro_utterances, "Target_Child")
shiro_mi_adults <- get_mi(shiro_utterances, "not child")

ggplot(shiro_mi_children, aes(x = pos1, y = mi, color = as.factor(pos2))) + 
  facet_wrap(~length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Mutual information vs. conditioned position (Shiro children)")

ggplot(shiro_mi_adults, aes(x = pos1, y = mi, color = as.factor(pos2))) + 
  facet_wrap(~length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Mutual information vs. conditioned position (Shiro adults)")


shiro_ce_children <- get_ce(shiro_utterances, "Target_Child")
shiro_ce_adults <- get_ce(shiro_utterances, "not child")

ggplot(shiro_ce_children, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Shiro children)")

ggplot(shiro_ce_adults, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Shiro adults)")


wagner_ce_children <- get_ce(wagner_utterances, "Target_Child")
wagner_ce_adults <- get_ce(wagner_utterances, "not child")

ggplot(wagner_ce_children, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Wagner children)")

ggplot(wagner_ce_adults, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Wagner adults)")


okayama_mi_children <- get_mi(okayama_utterances, "Target_Child")
okayama_mi_adults <- get_mi(okayama_utterances, "not child")

ggplot(okayama_mi_children, aes(x = pos1, y = mi, color = as.factor(pos2))) + 
  facet_wrap(~length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Mutual information vs. conditioned position (Okayama children)")

ggplot(okayama_mi_adults, aes(x = pos1, y = mi, color = as.factor(pos2))) + 
  facet_wrap(~length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Mutual information vs. conditioned position (Okayama adults)")

okayama_ce_children <- get_ce(okayama_utterances, "Target_Child")
okayama_ce_adults <- get_ce(okayama_utterances, "not child")

ggplot(okayama_ce_children, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Okayama children)")

ggplot(okayama_ce_adults, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Okayama adults)")


miipro_mi_children <- get_mi(miipro_utterances, "Target_Child")
miipro_mi_adults <- get_mi(miipro_utterances, "not child")

ggplot(miipro_mi_children, aes(x = pos1, y = mi, color = as.factor(pos2))) + 
  facet_wrap(~length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Mutual information vs. conditioned position (Miipro children)")

ggplot(miipro_mi_adults, aes(x = pos1, y = mi, color = as.factor(pos2))) + 
  facet_wrap(~length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Mutual information vs. conditioned position (Miipro adults)")

miipro_ce_children <- get_ce(miipro_utterances, "Target_Child")
miipro_ce_adults <- get_ce(miipro_utterances, "not child")

ggplot(miipro_ce_children, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Miipro children)")

ggplot(miipro_ce_adults, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Miipro adults)")


zhou_mi_children <- get_mi(zhou_dinner, "Target_Child")
zhou_mi_adults <- get_mi(zhou_dinner, "not child")

ggplot(zhou_mi_children, aes(x = pos1, y = mi, color = as.factor(pos2))) + 
  facet_wrap(~length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Mutual information vs. conditioned position (Zhou children)")

ggplot(zhou_mi_adults, aes(x = pos1, y = mi, color = as.factor(pos2))) + 
  facet_wrap(~length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Mutual information vs. conditioned position (Zhou adults)")

zhou_ce_children <- get_ce(zhou_dinner, "Target_Child")
zhou_ce_adults <- get_ce(zhou_dinner, "not child")

ggplot(zhou_ce_children, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Zhou children)")

ggplot(zhou_ce_adults, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Zhou adults)")


leveille_ce_children <- get_ce(leveille_utterances, "Target_Child")
leveille_ce_adults <- get_ce(leveille_utterances, "not child")

ggplot(leveille_ce_children, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Leveille children)")

ggplot(leveille_ce_adults, aes(x = X, y = ce, color = as.factor(Y))) + 
  facet_wrap(~ length) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Conditional entropy vs. conditioned random variable (Leveille adults)")
```
