---
title: "process_bnc"
output: html_document
---

```{r load_libraries}
library(tidyverse)
library(stringr)
library(feather)
library(here)
library(tidytext)

NEW_DIR = here("BNC_parsed")
```

You want to download the file from (http://ota.ox.ac.uk/desc/2554). Move it to the same directory as this .Rmd file

```{r parse_bnc, eval = F}  

files <- list.files(here("bnc/Texts"), "*.xml", full.names = T, recursive = T)

if(!dir.exists(NEW_DIR))
  dir.create(NEW_DIR)

parse_BNC <- function(file) {
  
  filename <- str_split(file, "/") %>% 
    unlist() %>% 
    last() %>% 
    str_split(., "\\.") %>%
    unlist() %>%
    first() %>%
    paste0(.,".txt")
  
  newname = paste0(NEW_DIR, "/", filename)

  print(file)
  
  system(paste0("xsltproc bnc/XML/Scripts/justTheWords.xsl ", file, " > ", newname))
}

map(files, parse_BNC)
```

```{r read_parsed_bnc}
files <- list.files(NEW_DIR,  "*.txt", full.names = T)

txt <- map(files, read_lines) %>%
  unlist() %>%
  enframe(name = NULL) %>%
  filter(value != "") %>%
  mutate(value = str_trim(gsub('[[:punct:] ]+',' ', value)))

write_feather(txt, "bnc/bnc.feather")
```

```{r post_process_bnc}
bnc_tokens <- read_feather(here("bnc/bnc.feather")) %>%
  mutate(length = str_count(value, pattern = " +") + 1) %>% 
  mutate(utterance_id = 1:n()) %>%
  unnest_tokens(word, value, token = stringr::str_split, pattern = "[ +]+") %>%
  group_by(utterance_id) %>%
  mutate(word_order = 1:n()) 

bnc_tokens %>%
  filter(length == 10) %>%
  write_feather(here("../bnc/bnc10.feather"))

bnc_tokens %>%
  filter(length == 20) %>%
  write_feather(here("../bnc/bnc20.feather"))

bnc_tokens %>%
  filter(length == 30) %>%
  write_feather(here("../bnc/bnc30.feather"))


```
