---
title: Non-English Conditional Entropy and Mutual Information
author: Josef Klafka
date: "`r Sys.date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show 
---

```{r setup, include=FALSE}
# load packages
library(DBI)
library(knitr)
library(tidyverse)
library(directlabels)
library(dplyr)

library(SnowballC) #stemmer
library(tidytext)
library(entropy)
library(tidyboot)
library(tokenizers)
library(tau)
library(gtools)
knitr::opts_chunk$set(echo = TRUE)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = FALSE, tidy = FALSE)

theme_set(theme_classic(base_size = 16))
```

```{r open_connection}
connect_to_ldp <- function() {
 DBI::dbConnect(RMySQL::MySQL(),
                host = "mysql.rcc.uchicago.edu",
                dbname = "ldp",
                user = "ldp_user",
                password = "d0aa6b5950e")
}

connection <- connect_to_ldp()

get_table <- function(connection, name) {
 dplyr::tbl(connection, name)
}

utterances <- get_table(connection, "utterances") %>% collect() #to get the "utterances" table as a dataframe named utterances
home_visits <- get_table(connection, "home_visits")  %>% collect() #information about SES, work, education and other demographic stuff
DBI::dbListTables(connection) #to list the tables in the collection
```

```{r filter_utterances}
get_ses_utterances <- function(status, utterances, home_visits) {
  ids <- home_visits %>% 
    filter(income_category %in% status)  %$% 
    id %>% 
    unique() %>% 
    unlist()
  
  utterances %>% filter(subject %in% ids)
}
```

```{r entropy}
get_unigram_entropies <- function(role, sen_length, utterances) {
  
  if(role == "child") {
    sub_utterances <- utterances %>%
      filter(c_utts_orig != "") %>%
      mutate(length = str_count(c_utts_orig, " |\\+|_") + 1)
      colnames(sub_utterances)[colnames(sub_utterances)=="c_utts_orig"] <- "gloss"
  } else {
     sub_utterances <- utterances %>%
      filter(p_utts_orig != "") %>%
      mutate(length = str_count(p_utts_orig, " |\\+|_") + 1) 
      colnames(sub_utterances)[colnames(sub_utterances)=="p_utts_orig"] <- "gloss"
  }
  
    tokens <- sub_utterances %>%
    filter(length == sen_length) %>%
    mutate(utterance_id = 1:n()) %>%
    unnest_tokens(word, gloss) %>%
    group_by(utterance_id) %>%
    mutate(word_order = 1:n()) %>%
    group_by(word_order, word) %>%
    mutate(clean_word = str_replace_all(tolower(word), "-|\\?|\\.|!|,", "")) %>%
    filter(word_order <= length) ##GO BACK AND FIX THIS LATER 
   
  tokens %>%
    summarise(n = n()) %>%
    tidyboot(summary_function = function(x) x %>% 
               summarise(entropy = entropy(n, unit = "log2")),
             statistics_functions = function(x) x %>%
             summarise_at(vars(entropy), funs(ci_upper, ci_lower))) %>%
    mutate(role = role, length = sen_length)
}
```

```{r ldp_analysis}
STATUS <- c(1)

ses_utts <- get_ses_utterances(STATUS, utterances, home_visits)

entropies_child <- map(2:10, ~get_unigram_entropies("child", .x, ses_utts)) %>%
  bind_rows()

ggplot(entropies_child, aes(x = word_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

entropies_adult <- map(2:10, ~get_unigram_entropies("not child", .x, ses_utts)) %>%
  bind_rows()

ggplot(entropies_adult, aes(x = word_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper)) +
  facet_wrap(~ length) + 
  geom_pointrange() +
  geom_smooth(se = F)

entropies_all <- bind_rows(entropies_adult, entropies_child)

ggplot(entropies_all, aes(x = word_order, y = empirical_entropy,
                      ymin = ci_lower, ymax = ci_upper, color = role)) +
  facet_wrap(~ length) + 
  geom_pointrange(position = position_dodge(.25)) +
  geom_smooth(se = F) +
  ggtitle("Child and Adult Entropy Distributions (LDP SES Bracket 1)")
```