---
title: Letter-level (orthographic) surprisal analysis
author: Josef Klafka and Dan Yurovsky
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show 
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytext)
library(childesr)

knitr::opts_chunk$set(echo = TRUE)
```


```{r set up corpus}
prov_utterances <- get_utterances(corpus = "Providence")

adult_utterances <- prov_utterances %>%
  filter(speaker_role != "Target_Child") %>% 
  mutate(utterance_id = 1:n()) %>% 
  unnest_tokens(word, gloss, token = stringr::str_split, pattern = "[ +]+") %>%
  group_by(utterance_id) %>%
  mutate(word_id = 1:n()) %>%
  ungroup() %>%
  unnest_tokens(letter, word, token = stringr::str_split, pattern = "", drop = F) %>%
  group_by(utterance_id, word_id) %>%
  mutate(letter_order = 1:n()) %>%
  mutate(word_length = max(letter_order)) %>%
  ungroup()
```

```{r unigrams}
letter_probs <- adult_utterances %>% 
  count(letter) %>%
  ungroup() %>%
  mutate(p = n/sum(n))

letter_unigrams <- adult_utterances %>% 
  left_join(letter_probs) %>%
  mutate(s = -log(p)) %>%
  group_by(word_length, letter_order) %>%
  summarise(mean_s = mean(s))
```

```{r childes bigrams}
bigram_probs <- adult_utterances %>% 
  group_by(utterance_id) %>%
  mutate(lag_letter = lag(letter)) %>%
  group_by(lag_letter, letter) %>%
  count() %>%
  filter(!is.na(lag_letter)) %>%
  ungroup() %>%
  left_join(letter_probs, by = c("lag_letter" = "letter")) %>%
  mutate(cond_p = n.x / n.y) %>%
  select(lag_letter, letter, cond_p, n.x) %>%
  rename(n = n.x)

letter_bigrams <- adult_utterances %>%
  group_by(utterance_id, word_id) %>%
  mutate(lag_letter = lag(letter)) %>%
  ungroup() %>%
  left_join(bigram_probs, by = c("lag_letter" = "lag_letter", "letter" = "letter")) %>%
  left_join(letter_probs, by = c("letter" = "letter")) %>%
  mutate(s = ifelse(is.na(lag_letter), -log(p), -log(cond_p))) %>%
  group_by(word_length, letter_order) %>%
  summarise(mean_s = mean(s)) 
```

```{r childes trigrams}
trigram_probs <- adult_utterances %>%
  group_by(utterance_id, word_id) %>%
  mutate(lag_letter1 = lag(letter)) %>%
  mutate(lag_letter2 = lag(lag_letter1)) %>%
  group_by(lag_letter2, lag_letter1, letter) %>%
  count() %>%
  filter(!is.na(lag_letter1), !is.na(lag_letter2)) %>%
  ungroup() %>%
  left_join(bigram_probs, by = c("lag_letter2" = "lag_letter", "lag_letter1" = "letter")) %>%
  mutate(tri_cond_p = n.x / n.y) %>%
  select(-cond_p, -n.y) %>%
  rename(n = n.x)


letter_trigrams <- adult_utterances %>%
  group_by(utterance_id, word_id) %>%
  mutate(lag_letter1 = lag(letter)) %>%
  mutate(lag_letter2 = lag(lag_letter1)) %>%
  left_join(trigram_probs, by = c("lag_letter2" = "lag_letter2", "lag_letter1" = "lag_letter1", "letter" = "letter")) %>% 
  left_join(bigram_probs, by = c("lag_letter1" = "lag_letter", "letter" = "letter")) %>% 
  left_join(letter_probs, by = c("letter" = "letter")) %>%
  mutate(s = ifelse(is.na(lag_letter2), # check if it's not the first word
                    ifelse(is.na(lag_letter1), # check if not the second word
                           -log(p), # trigram if third or beyond
                           -log(cond_p)), # bigram if second word
                    -log(tri_cond_p))) %>% # unigram if first word
  group_by(word_length, letter_order) %>%
  summarise(mean_s = mean(s)) %>% 
  filter(letter_order <= word_length)
```

```{r plot results}
letter_unigrams %>%
  filter(word_length %in% 3:11) %>%
  ggplot(aes(x = letter_order, y = mean_s)) + 
    facet_wrap(~word_length) + 
    geom_point() +
    geom_line() + 
    xlab("Letter Position") + 
    ylab("Mean surprisal")
```