---
title: "Phoneme surprisal"
author: Josef Klafka and Dan Yurovsky 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show 
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(tidytext)
library(tidyverse)
library(childesr)
library(glue)
library(feather)
library(here)
library(entropy)
library(tidyboot)
library(janitor)
library(arrangements)

knitr::opts_chunk$set(echo = TRUE)
```

```{r prov phonemes, eval = F, include = F}
system("rm words.txt phones.txt splitphones.txt joined.csv")
adult_utterances %>%
  distinct(word) %>%
  filter(word != "", word != "tʃutʃutʃu", word != "ɛː", word != "lunchroom", word != "dryad's", word != "vi") %>%
  pull(word) %>%
  write_lines("words.txt")

system("espeak -f words.txt --ipa=3 -v fr -q --phonout='phones.txt'") #get the ipa of each word
system("cat phones.txt | sed -E 's/ /|/g' | tr '|' '\n' | tail -n +2 > splitphones.txt") #put each ipa word onto its own line in a file called splitphones.txt
system("rm phones.txt")
system("sed '/^$/d' splitphones.txt > phones.txt") #remove empty lines in splitphones
system("paste -d , words.txt phones.txt > joined.csv") #make csv with words and their ipa paired

```

```{r read_phonemes, include = F}
prov_utterances <- get_utterances(corpus = "Providence") #stem or gloss

adult_utterances <- prov_utterances %>%
  filter(speaker_role != "Target_Child") %>% 
  mutate(utterance_id = 1:n()) %>% 
  unnest_tokens(word, stem, token = stringr::str_split, pattern = "[ +]|[_+]+") %>%
  group_by(utterance_id) %>%
  mutate(word_id = 1:n())

system("rm words.txt phones.txt splitphones.txt joined.csv")
adult_utterances %>%
  filter(word != "", word != "tʃutʃutʃu", word != "ɛː", word != "lunchroom", word != "dryad's", word != "vi") %>%
  pull(word) %>%
  unique() %>%
  write_lines("words.txt")

system("espeak -f words.txt --ipa=3 -v en-us -q --phonout='phones.txt'") #get the ipa of each word
system("cat phones.txt | sed -E 's/ /|/g' | tr '|' '\n' | tail -n +2 > splitphones.txt") #put each ipa word onto its own line in a file called splitphones.txt
system("rm phones.txt")
system("sed '/^$/d' splitphones.txt > phones.txt") #remove empty lines in splitphones
system("paste -d , words.txt phones.txt > joined.csv") #make csv with words and their ipa paired

phones <- read_csv("joined.csv",
                   col_names = c("word", "ipa"))

adult_phonemes <- adult_utterances %>%
  left_join(phones) %>%
  filter(!is.na(ipa)) %>%
  unnest_tokens(phone, ipa, token = stringr::str_split, 
                pattern = "_+", drop = F) %>%
  filter(phone != "") %>%
  group_by(utterance_id, word_id) %>%
  mutate(phone_order = 1:n()) %>%
  mutate(word_length = max(phone_order)) %>%
  ungroup() %>%
  select(utterance_id, word_id, word, ipa, phone, phone_order, word_length)

adult_phonemes %>% write_feather(here("Data/adult_phonemes.feather"))

adult_phonemes %>%
  filter(phone_order == 1) %>%
  ggplot(aes(x = word_length)) + 
  geom_histogram(fill = "white", color = "black", binwidth = 1) + 
  theme_classic()

phone_probs <- adult_phonemes %>% 
  count(phone) %>%
  ungroup() %>%
  mutate(p = n/sum(n))

ipa_unigrams <- adult_phonemes %>% 
  left_join(phone_probs) %>%
  mutate(s = -log(p)) %>%
  group_by(word_length, phone_order) %>%
  summarise(mean_s = mean(s))
```

```{r childes unigrams}
phone_probs <- adult_phonemes %>% 
  count(phone) %>%
  ungroup() %>%
  mutate(p = n/sum(n))

phone_unigrams <- adult_phonemes %>% 
  left_join(phone_probs) %>%
  mutate(s = -log(p)) %>%
  group_by(word_length, phone_order) %>%
  summarise(mean_s = mean(s))
```

```{r childes bigrams}
bigram_probs <- adult_phonemes %>% 
  group_by(utterance_id) %>%
  mutate(lag_phone = lag(phone)) %>%
  group_by(lag_phone, phone) %>%
  count() %>%
  filter(!is.na(lag_phone)) %>%
  ungroup() %>%
  left_join(phone_probs, by = c("lag_phone" = "phone")) %>%
  mutate(cond_p = n.x / n.y) %>%
  select(lag_phone, phone, cond_p, n.x) %>%
  rename(n = n.x)

phone_bigrams <- adult_phonemes %>%
  group_by(utterance_id, word_id) %>%
  mutate(lag_phone = lag(phone)) %>%
  ungroup() %>%
  left_join(bigram_probs, by = c("lag_phone" = "lag_phone", "phone" = "phone")) %>%
  left_join(phone_probs, by = c("phone" = "phone")) %>%
  mutate(s = ifelse(is.na(lag_phone), -log(p), -log(cond_p))) %>%
  group_by(word_length, phone_order) %>%
  summarise(mean_s = mean(s)) 
```

```{r childes trigrams}
trigram_probs <- adult_phonemes %>%
  group_by(utterance_id, word_id) %>%
  mutate(lag_phone1 = lag(phone)) %>%
  mutate(lag_phone2 = lag(lag_phone1)) %>%
  group_by(lag_phone2, lag_phone1, phone) %>%
  count() %>%
  filter(!is.na(lag_phone1), !is.na(lag_phone2)) %>%
  ungroup() %>%
  left_join(bigram_probs, by = c("lag_phone2" = "lag_phone", "lag_phone1" = "phone")) %>%
  mutate(tri_cond_p = n.x / n.y) %>%
  select(-cond_p, -n.y) %>%
  rename(n = n.x)


phone_trigrams <- adult_phonemes %>%
  group_by(utterance_id, word_id) %>%
  mutate(lag_phone1 = lag(phone)) %>%
  mutate(lag_phone2 = lag(lag_phone1)) %>%
  left_join(trigram_probs, by = c("lag_phone2" = "lag_phone2", "lag_phone1" = "lag_phone1", "phone" = "phone")) %>% 
  left_join(bigram_probs, by = c("lag_phone1" = "lag_phone", "phone" = "phone")) %>% 
  left_join(phone_probs, by = c("phone" = "phone")) %>%
  mutate(s = ifelse(is.na(lag_phone2), # check if it's not the first word
                    ifelse(is.na(lag_phone1), # check if not the second word
                           -log(p), # trigram if third or beyond
                           -log(cond_p)), # bigram if second word
                    -log(tri_cond_p))) %>% # unigram if first word
  group_by(word_length, phone_order) %>%
  summarise(mean_s = mean(s)) %>% 
  filter(phone_order <= word_length)

phone_unigrams <- phone_unigrams %>% mutate(gram = "Unigram") 
phone_bigrams <- phone_bigrams %>% mutate(gram = "Bigram") 
phone_trigrams <- phone_trigrams %>% mutate(gram = "Trigram") 
phone_unigrams %>% bind_rows(phone_bigrams, phone_trigrams) %>% write_feather(here("Data/palasis_phones.feather"))
```

```{r plot unigrams}
ipa_unigrams %>%
  filter(word_length %in% 2:6) %>%
  ggplot(aes(x = phone_order, y = mean_s)) +
    facet_wrap(~word_length) +
    geom_point() +
    geom_line() +
    xlab("Phone Position") +
    ylab("Mean surprisal")
```

```{r leave-out-surprisal, include = F}
hold_out_entropy <- function(df) {
  spread_df <- df %>%
    spread(phone_order, phone) %>%
    clean_names()
  
  phone_length <- max(df$phone_order)
  
  lens <- paste0("x", 1:phone_length)
  
  boot_entropy <- function(group) {
    spread_df %>%
      group_by_at(group) %>%
      summarise(n = n()) %>%
      summarise(entropy = entropy(n)) %>%
      ungroup() %>%
      tidyboot_mean(entropy)
  }
  
  
  groupings <- combinations(lens, phone_length -1, 
                            layout = "list") 
  
  groupings <- map(seq(length(lens),1,-1),
                   function(x) c(groupings[[x]], lens[x]))
  
  map_df(groupings, boot_entropy) %>%
    mutate(phone_order = seq(phone_length, 1, -1))
  
}
```


```{r show leave-out-entropy}
split_lengths <- adult_phonemes %>%
  group_by(word_length) %>%
  nest() %>%
  filter(word_length > 1) %>%
  filter(word_length %in% 1:6 ) %>%
  mutate(entropy = map(data, hold_out_entropy))

split_lengths %>%
  select(-data) %>%
  unnest() %>%
  ggplot(aes(x = phone_order, y = empirical_stat)) + 
  facet_wrap(~ word_length, scales = "free") +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) + 
  theme_classic() + 
  geom_line() + 
  xlab("Phone position") + 
  ylab("Entropy")
```
