---
title: Positional surprisal (1-3grams) in adultES corpora
author: Josef Klafka and Dan Yurovsky 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show 
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytext)
library(childesr)
library(ggthemes)
library(feather)

knitr::opts_chunk$set(echo = TRUE)
```

```{r pos unigrams}
prov_utterances <- get_utterances(corpus = "Providence") #stem or gloss
zhou_utterances <- get_utterances(corpus = "ZhouDinner")
okayama_utterances <- get_utterances(corpus = "Okayama")

adult_utterances <- prov_utterances %>%
  filter(speaker_role != "Target_adult") %>% 
  mutate(length = str_count(part_of_speech, pattern = "[ +]+") + 1) %>%
  mutate(utterance_id = 1:n()) %>%
  unnest_tokens(word, part_of_speech, token = stringr::str_split, pattern = "[ +]+") %>%
  group_by(utterance_id) %>%
  mutate(word_order = 1:n())

adult_unigrams <- adult_utterances %>%
  group_by(word) %>%
  count() %>%
  ungroup() %>%
  mutate(p = n / sum(n))
  
adult_surprisals <- adult_utterances %>%
  left_join(adult_unigrams) %>%
  mutate(s = -log(p)) %>%
  group_by(length, word_order) %>%
  summarise(mean = mean(s),
            median = median(s),
            se = sd(s)/sqrt(n()))

adult_surprisals %>%  
  filter(length %in% 4:9) %>%
  ggplot(aes(x = word_order, y = mean)) +
    facet_wrap(~length, scales = "free") + 
    ggtitle("Adult unigram POS surprisals") + 
    xlab("Word position") +
    ylab("Mean surprisal") +
    # scale_x_continuous(breaks = 1:7) + 
    geom_line(size = 1) +
    geom_pointrange(aes(ymin = mean - 1.96 * se, ymax = mean + 1.96 * se)) + 
    theme_classic(base_size = 10) + 
    scale_color_ptol() +
    theme(legend.position = "nones")
```

```{r pos bigrams}
adult_bigrams_prep <- adult_utterances %>% 
  group_by(utterance_id) %>%
  mutate(lag_word = lag(word)) %>%
  group_by(lag_word, word) %>%
  count() %>%
  filter(!is.na(lag_word)) %>%
  ungroup() %>%
  left_join(adult_unigrams, by = c("lag_word" = "word")) %>%
  mutate(cond_p = n.x / n.y) %>%
  select(lag_word, word, cond_p, n.x) %>%
  rename(n = n.x)

adult_bigrams <- adult_utterances %>%
  group_by(utterance_id) %>%
  mutate(lag_word = lag(word)) %>%
  ungroup() %>%
  left_join(adult_unigrams) %>%
  left_join(select(adult_bigrams_prep, -n), by = c("lag_word" = "lag_word", "word" = "word")) %>%
  mutate(s = ifelse(is.na(lag_word), -log(p), -log(cond_p))) %>%
  group_by(length, word_order) %>%
  summarise(mean_s = mean(s))

adult_bigrams %>%  
  filter(length %in% 4:9) %>%
  ggplot(aes(x = word_order, y = mean_s)) +
    facet_wrap(~length, scales = "free") + 
    ggtitle("Adult bigram POS surprisals") + 
    xlab("Word position") +
    ylab("Mean surprisal") +
    # scale_x_continuous(breaks = 1:7) + 
    geom_line(size = 1) +
    geom_point() + 
    # geom_pointrange(aes(ymin = mean - 1.96 * se, ymax = mean + 1.96 * se)) + 
    theme_classic(base_size = 10) + 
    scale_color_ptol() +
    theme(legend.position = "nones")
```

```{r pos trigrams}
adult_trigrams <- adult_utterances %>%
  group_by(utterance_id) %>%
  mutate(lag_word1 = lag(word)) %>%
  mutate(lag_word2 = lag(lag_word1)) %>%
  group_by(lag_word2, lag_word1, word) %>%
  count() %>%
  filter(!is.na(lag_word1), !is.na(lag_word2)) %>%
  ungroup() %>%
  left_join(adult_bigrams_prep, by = c("lag_word2" = "lag_word", "lag_word1" = "word")) %>%
  mutate(tri_cond_p = n.x / n.y) %>%
  select(lag_word2, lag_word1, word, tri_cond_p)


trigram_surprisals_prep <- adult_utterances %>%
  group_by(utterance_id) %>%
  mutate(lag_word1 = lag(word)) %>%
  mutate(lag_word2 = lag(lag_word1)) %>%
  left_join(adult_trigrams) %>% 
  left_join(select(adult_bigrams_prep, lag_word, word, cond_p), by = c("lag_word1" = "lag_word", "word" = "word")) %>% 
  left_join(adult_unigrams)


trigram_surprisals <- trigram_surprisals_prep %>%
  mutate(s = ifelse(is.na(lag_word2), # check if it's not the first word
                    ifelse(is.na(lag_word1), # check if not the second word
                           -log(p), # trigram if third or beyond
                           -log(cond_p)), # bigram if second word
                    -log(tri_cond_p))) %>% # unigram if first word
  group_by(length, word_order) %>%
  summarise(mean_s = mean(s)) %>% 
  filter(word_order <= length)

trigram_surprisals %>%  
  filter(length %in% 4:9) %>%
  ggplot(aes(x = word_order, y = mean_s)) +
    facet_wrap(~length, scales = "free") +
    ggtitle("Adult trigram POS surprisals") + 
    xlab("Word position") +
    ylab("Mean surprisal") +
    # scale_x_continuous(breaks = 1:7) + 
    geom_line(size = 1) +
    geom_point() + 
    # geom_pointrange(aes(ymin = mean - 1.96 * se, ymax = mean + 1.96 * se)) + 
    theme_classic(base_size = 10) + 
    scale_color_ptol() +
    theme(legend.position = "nones")
```