---
title: "Kneser-Ney smoothing"
author: "Josef Klafka and Dan Yurovsky"
date: "9/17/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytext)
library(tidyboot)
library(childesr)

knitr::opts_chunk$set(echo = TRUE)
```

```{r set up}

child_utterances <- get_utterances(corpus = "Providence") %>%
  filter(speaker_role == "Target_Child") %>% 
  mutate(length = str_count(stem, pattern = "[ +]+") + 1) %>%
  mutate(utterance_id = 1:n()) %>%
  unnest_tokens(word, stem, token = stringr::str_split, pattern = "[ +]+") %>%
  group_by(utterance_id) %>%
  mutate(word_order = 1:n()) %>%
  ungroup()

vocab_size <- child_utterances %>%
  ungroup() %>%
  distinct(word) %>% 
  nrow()

child_unigrams <- child_utterances %>%
  count(word) %>%
  mutate(p = (n + 1) / (sum(n) + vocab_size))

child <- child_utterances %>%
  left_join(child_unigrams, by = "word") %>%
  mutate(s = -log(p)) %>%
  ungroup() %>%
  select(length, word_order, s) %>%
  filter(length %in% c(5, 7, 9)) %>%
  group_by(length, word_order) %>%
  nest()

child %>%
  mutate(surprisal = map(data, ~tidyboot_mean(.x, s, nboot = 10))) %>%
  select(-data) %>%
  unnest(cols = c(surprisal)) %>%
  ggplot(aes(x = word_order, y = empirical_stat, color = as.factor(length))) + 
    geom_point() +
    geom_line()

# by-word: number of times w_i is unique continuation / number of unique continuations overall
continuations <- child_utterances %>%
  group_by(utterance_id) %>%
  mutate(lag_word = lag(word)) %>%
  ungroup() %>%
  select(lag_word, word) %>%
  filter(!is.na(lag_word)) %>%
  distinct() %>%
  count(word) %>%
  mutate(cont_p = n/sum(n)) %>%
  select(-p)
  
child_bigrams <- child_utterances %>%
  group_by(utterance_id) %>%
  mutate(lag_word = lag(word)) %>%
  group_by(lag_word, word) %>%
  count() %>%
  filter(!is.na(lag_word)) %>%
  ungroup() %>%
  left_join(child_unigrams, by = c("lag_word" = "word")) %>%
  mutate(cond_p = (n.x + 1)  / (n.y + vocab_size)) 

```