---
title: Wikipedia Text Mining and Surprisal Analysis
author: Josef Klafka and Dan Yurovsky
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show 
---

```{r setup, include=FALSE}
library(tidyverse)
library(googlesheets)
library(lingtypology)
library(knitr)
library(missMDA)
library(cluster)
library(widyr)
library(lsa)
library(magrittr)
library(broom)
library(here)
library(feather)
library(FactoMineR)
library(feather)
library(janitor)
library(ggdendro)

knitr::opts_chunk$set(echo = TRUE)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = FALSE, tidy = FALSE)

theme_set(theme_classic(base_size = 16))
```

```{r make dendrogram}
wiki <- read.csv(here("Data/wikipedia_0context.csv")) %>%
  select(-X) %>% 
  column_to_rownames("Language")

wiki %>% 
  dist() %>% 
  hclust() %>% 
  ggdendrogram(rotate = FALSE, size = .1) + 
  ylim(0, .10)

  plot(hang = -1, 
       main = "Dendrogram of slope embeddings")

```

```{r word order}
wkpd <- read.csv(here("Data/wikipedia_0context.csv"))
LANGUAGES <- wkpd$Language


FEATURES <- c(1:144)
for (i in c(1:length(FEATURES))) {
  FEATURES[i] <- paste(FEATURES[i], "A", sep = "")
} #get all word order WALS features in correct syntax

wf <- wals.feature(FEATURES) 

# word order
# wo_wf <- wf %>% 
#   filter(language %in% LANGUAGES) %>%
#   select(language, `82A`:`97A`) %>%
#   select(-`84A`)

# nominal categories
wo_wf <- wf %>%
  filter(language %in% LANGUAGES) %>%
  select(language, `30A`:`57A`) #%>%
wo_wf$non <- rowSums(is.na(wo_wf))
wo_wf %<>%
  filter(non < 12) %>%
  select(-non)

wo_df <- wo_wf %>%
  as_data_frame() %>%
  group_by(language) %>%
  slice(1) %>%
  gather(feature, value, `30A`:`57A`) %>%
  group_by(feature) %>%
  mutate(value = factor(value))

imputed_wo <- wo_df %>%
  select(language, feature, value) %>%
  ungroup() %>% 
  spread(feature, value) %>% 
  column_to_rownames("language") %>%
  sapply(as.factor) %>%
  MIMCA(ncp = 1)

imputed_wo <- as.data.frame(imputed_wo[[1]][[99]]) 

wo_sub <- imputed_wo %>% group_by(language) %>%
  slice(1) %>%
  gather(feature, value, `30A`:`57A`) %>%
  group_by(feature) %>%
  mutate(value = as.numeric(as.factor(value)))

cosines <- wkpd %>%
  column_to_rownames("Language") %>%
  t() %>%
  cosine() %>%
  as_data_frame(rownames = "language1") %>%
  gather(language2, cosine, -language1)

wf_pairwise <- expand.grid(language1 = wo_sub$language,
                           language2 = wo_sub$language) %>%
  left_join(wo_sub, by = c("language1" = "language")) %>%
  rename(value1 = value) %>%
  left_join(wo_sub, by = c("language2" = "language", "feature")) %>%
  rename(value2 = value) %>%
  mutate(same = value1 == value2) %>%
  select(-value1, -value2) %>%
  left_join(cosines, by = c("language1", "language2"))

models <- wf_pairwise %>%
  group_by(feature) %>%
  nest() %>%
  mutate(model = map(data, ~glm(same ~ cosine, 
                                family = "binomial", data = .)))

feature_names <- read_feather(here("Wikipedia/feature_names.feather"))

model_df <- models %>%
  mutate(coeffs = map(model, tidy)) %>%
  select(-data, -model) %>%
  unnest() %>%
  filter(term == "cosine") %>%
  arrange(desc(statistic)) %>%
  left_join(feature_names)
```